language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install

# before_script:

script:
  - npm run deploy

# after_script:

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/dmego/dmego.github.io.git --{仓库地址}